In [3]:
import tensorflow as tf

print(f"Tensorflow 버전확인 : {tf.__version__}")

Tensorflow 버전확인 : 2.15.0


# 텐서플로우로 텐서 만들기

In [7]:
#정수 상수 텐서 : 값을 변경할 수 없음
tensor_int = tf.constant(5, dtype=tf.int32)
print(tensor_int)

tensor1 = tf.constant([5, 3])
print(tensor1)

tensor1 = tf.constant([50, 30])
print(tensor1)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([5 3], shape=(2,), dtype=int32)
tf.Tensor([50 30], shape=(2,), dtype=int32)


In [9]:
#변수 텐서 생성
tensor2 = tf.Variable(5)
print(tensor2)

#변수 텐서의 값 변경
tensor2.assign(10)

print(tensor2)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


## 4) 넘파이 배열을 텐서로 변환

In [10]:
import numpy as np
import tensorflow as tf

In [19]:
numpy_arr = np.array([1, 2, 3, 4])
print(numpy_arr, numpy_arr.dtype, type(numpy_arr))

tensor1 = tf.convert_to_tensor(numpy_arr)
print(tensor1, tensor1.dtype, type(tensor1))
#tensor 변수는 텐서플로우에서 사용되는 텐서 데이터 구조

[1 2 3 4] int32 <class 'numpy.ndarray'>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) <dtype: 'int32'> <class 'tensorflow.python.framework.ops.EagerTensor'>


In [21]:
#리스트를 텐서로 변환
li = [1, 3, 5.52, 7, 9]
print(li, type(li))

tensor2 = tf.convert_to_tensor(li)
print(tensor2, type(tensor2))
#리스트는 모든 자료형을 허용하지만 텐서는 실수, 정수일 때만 사용 가능하다

[1, 3, 5.52, 7, 9] <class 'list'>
tf.Tensor([1.   3.   5.52 7.   9.  ], shape=(5,), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>


## 5) 텐서를 넘파이 배열로 변환

In [14]:
numpy_ar = tensor1.numpy()
print(numpy_ar, type(numpy_ar))

[1 2 3 4] <class 'numpy.ndarray'>


## 6) 텐서플로우 함수

In [22]:
#두 정수 텐서 생성
tensor1 = tf.constant(5, dtype=tf.int32)
tensor2 = tf.constant(7, dtype=tf.int32)

#텐서 덧셈 연산
result = tf.add(tensor1, tensor2)
print(result)

tf.Tensor(12, shape=(), dtype=int32)


In [23]:
#행렬 곱셈 연산

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

result1 = tf.matmul(matrix1, matrix2)
print(result1)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [24]:
print(result1.numpy())

[[19 22]
 [43 50]]


In [28]:
#텐서 슬라이싱 연산

#2차원 텐서 생성
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor)

slice_tensor = tensor[0:2, 1:3]
print(slice_tensor)
print(slice_tensor.numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
[[2 3]
 [5 6]]


In [ ]:
#활성화 함수 : 인공신경망에서 각 뉴런의 출력을 결정하는 함수
# 뉴런의 입력을 받아 어떤 임계값을 기준으로 출력을 결정하는 함수
# 비선형을 추가하여 신경망이 복잡한 모델링하거나 다양한 문제를 해결할 수 있도록함
# ReLU(Recitified Linear Unit) : 은닉층에서 주로 사용, 양수일 경우 그 값 출력, 
#음수일경우 0으로 출력하는 함수


In [29]:
#실수 텐서 생성
tensor3 = tf.constant([-4.14, 2.53, 5.33, 0.05])

relu = tf.nn.relu(tensor3)
print("활성화 함수 적용 결과")
print(relu.numpy())

활성화 함수 적용 결과
[0.   2.53 5.33 0.05]


In [30]:
#텐서 크기 변경

#1차원 텐서
tensor = tf.constant([1, 2, 3, 4, 5, 6])

tensor_re = tf.reshape(tensor, (2, 3))
print(tensor_re)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [31]:
#모든 요소가 1인 텐서 생성
one_tf = tf.ones((4, 3))
print(one_tf.numpy())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#모든 요소가 0인 텐서 생성
zeros_tf = tf.zeros((5, 2))
print(zeros_tf)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(5, 2), dtype=float32)


In [33]:
#주어진 값으로 모든 요소를 채운 텐서 생성하는 함수
fill_tf = tf.fill((4, 6), 3)
print(fill_tf.numpy())

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


In [37]:
tf1 = tf.constant([[2, 4.5],[5.2, 53]])
print(tf1)
print(tf1.numpy())

tf2 = tf.zeros_like(tf1)
print(tf2)

tf3 = tf.ones_like(tf1)
print(tf3)

tf.Tensor(
[[ 2.   4.5]
 [ 5.2 53. ]], shape=(2, 2), dtype=float32)
[[ 2.   4.5]
 [ 5.2 53. ]]
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [56]:
tf4 = tf.range(10)
print(tf4)

#0~1사이의 랜덤한 값을 2행 2열로 추출
tf5 = tf.random.uniform((2, 2))
print(tf5)

#정규분포 난수를 3행 2열로 추출
tf6 = tf.random.normal((3, 2))
print(tf6)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0.81680226 0.86328495]
 [0.138219   0.15061057]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.74406505 -0.90292567]
 [ 0.6332105  -1.9844692 ]
 [-1.4267209  -0.02349401]], shape=(3, 2), dtype=float32)


## 7) 텐서의 속성

In [59]:
t1 = tf.random.normal((3, 4))
print(t1)
print(t1.shape)
print(t1.dtype)


tf.Tensor(
[[-0.8647456   1.615052   -1.1073326  -0.76404846]
 [ 1.5331246   1.7867993   0.5094841   0.27155465]
 [-1.5917287   0.9521845  -0.07906055  0.76146066]], shape=(3, 4), dtype=float32)
(3, 4)
<dtype: 'float32'>


In [60]:
#.cast(텐서, 변경할 타입) : 텐서의 각 요소 타입 변경
t2 = tf.cast(t1, tf.int32)
print(t2)

tf.Tensor(
[[ 0  1 -1  0]
 [ 1  1  0  0]
 [-1  0  0  0]], shape=(3, 4), dtype=int32)
