# 1. 붓꽃 데이터
## 학습 데이터로 잘못된 예측 케이스

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

## 데이터 로드

In [3]:
iris = load_iris()

#학습 데이터 세팅
train_data = iris.data
train_label = iris.target

In [5]:
print(train_data.shape)
print(train_label.shape)

(150, 4)
(150,)


## 모델학습

In [6]:
dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [7]:
#학습데이터로 학습
dt.fit(train_data, train_label)

DecisionTreeClassifier()

In [9]:
y_pred = dt.predict(train_data)
print(f"예측 정확도 : {accuracy_score(train_label, y_pred)}")

예측 정확도 : 1.0


In [10]:
train_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 정확도 확인시 1.0(100%)의 값이 나옴
### 과적합 되었음을 예측할 수 있고, 실제값으로 확인 가능함
### train_test_split을 이용해 테스트셋의 비율을 나누어 확인

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
dt1 = DecisionTreeClassifier()
iris_data = load_iris()

## 데이터셋 분할

In [21]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size = 0.2, random_state = 123)


In [30]:
print(X_train.shape)
print(X_test.shape)
y_train
y_test

(120, 4)
(30, 4)


array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

## 모델학습

In [23]:
dt1.fit(X_train, y_train)
y_pred = dt1.predict(X_test)
print(f"예측정확도 : {accuracy_score(y_test, y_pred)}")

예측정확도 : 0.9333333333333333


In [31]:
y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1,
       0, 2, 0, 0, 0, 2, 2, 0])

In [32]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

# 교차검증(K-Fold)

In [36]:
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd

In [38]:
#데이터로드
iris = load_iris()
label = iris.target
features = iris.data
print(features.shape)

(150, 4)


In [39]:
# 모델 정의
dt = DecisionTreeClassifier(random_state = 100)
dt

DecisionTreeClassifier(random_state=100)

In [59]:
#K-Folde
#5개의 폴드세트로 분리하는 kfold 객체, 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits = 5)
print(kfold)
# n_splits : 몇개로 분할할지
#random_state=None #나눈 Fold를 그대로 사용할 지
#shuffle=False : Fold를 나누기 전에 무작위로 섞을 지

cv = [] #5번 교차검증의 평균 정확도를 계산하기 위한 리스트
print(f"붓꽃 데이터 세트 크기 : {features.shape[0]}")

KFold(n_splits=5, random_state=None, shuffle=False)
붓꽃 데이터 세트 크기 : 150


In [61]:
print(kfold.split(features)) #features 입력 데이터를 나타내는 변수
#.split() 데이터를 분할하여 각 폴드의 인덱스를 반환

<generator object _BaseKFold.split at 0x000002268CD75360>


In [62]:
#kfold 객체의 split() 호출하면 학습, 검증 테스트의 행 인덱스를 array로 반환
# for i in kfold.split(features):
#     print(i)

for train_index, test_index in kfold.split(features):
    print(f"train index = {train_index}\ntest index = {test_index}")

train index = [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
test index = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
train index = [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 

In [63]:
n_iter = 0 #반복횟수를 나타내는 변수

for train_index, test_index in kfold.split(features):
    #kfold.split(features) : 학습 데이터와 검증 데이터의 인덱스
    #train_index : 학습 데이터의 인덱스 배열
    #test_index : 검증 데이터의 인덱스 배열
    
    #데이터 분할
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    #학습
    dt.fit(X_train, y_train)
    #예측
    y_pred = dt.predict(X_test)
    n_iter += 1
    
    #반복시마다 정확도 측정
    acc = np.round(accuracy_score(y_test, y_pred),5)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f"{n_iter} 교차검증 정확도 : {acc}, 학습데이터 크기 : {train_size}, 검증데이터 크기 : { test_size}")
    print(f"{n_iter} 검증 세트 인덱스 : {test_index}")
    cv.append(acc)

print(cv)

1 교차검증 정확도 : 1.0, 학습데이터 크기 : 120, 검증데이터 크기 : 30
1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2 교차검증 정확도 : 0.96667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3 교차검증 정확도 : 0.9, 학습데이터 크기 : 120, 검증데이터 크기 : 30
3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4 교차검증 정확도 : 0.93333, 학습데이터 크기 : 120, 검증데이터 크기 : 30
4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5 교차검증 정확도 : 0.73333, 학습데이터 크기 : 120, 검증데이터 크기 : 30
5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[1.0, 0.96667, 0.9, 0.93333, 0.73333]


In [64]:
#개별 정확도를 합하여 평균 정확도 계산
print(f"평균 검증 정확도 : {np.mean(cv)}")


평균 검증 정확도 : 0.9066659999999999


# knn 알고리즘으로 학습

In [72]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

iris = load_iris()
iris
features = iris.data
label = iris.target

#K-폴드 교차 검증 생성
kfold = KFold(n_splits = 5, shuffle = True, random_state = 42)

#K-최근접 이웃 분류기 생성
knn = KNeighborsClassifier(n_neighbors = 3)

#교차검증 및 정확도 기록
n_iter = 0 #반복횟수를 나타내는 변수
cv = [] #교차 검증 결과를 저장할 리스트

for train_index, test_index in kfold.split(features):
    #데이터 분할
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    #학습
    knn.fit(X_train, y_train)
    
    #예측
    y_pred = knn.predict(X_test)
    
    n_iter += 1
    
    #반복 시마다 정확도 측정
    acc = np.round(accuracy_score(y_test, y_pred), 5)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f"{n_iter}교차검증 정확도 : {acc}, 학습 데이터 크기 : {train_size}, 테스트데이터 크기 : {test_size}")
    print(f"{n_iter} 검증세트 인덱스 : {test_index}")
    cv.append(acc)
    
print(cv)
#개별 정확도 합하여 평균 정확도 계산
print(f"평균 검증 정확도 : {np.mean(cv)}")

1교차검증 정확도 : 1.0, 학습 데이터 크기 : 120, 테스트데이터 크기 : 30
1 검증세트 인덱스 : [  9  12  18  19  26  29  30  31  36  45  55  56  64  68  69  73  76  78
  82 104 108 110 118 127 128 131 132 141 143 145]
2교차검증 정확도 : 0.96667, 학습 데이터 크기 : 120, 테스트데이터 크기 : 30
2 검증세트 인덱스 : [  0   4  10  11  15  16  22  27  28  32  40  42  44  51  60  65  66  67
  75  81  85  86  96 105 109 122 133 137 142 146]
3교차검증 정확도 : 0.96667, 학습 데이터 크기 : 120, 테스트데이터 크기 : 30
3 검증세트 인덱스 : [  5   7  23  24  25  33  34  35  39  43  47  49  53  62  70  77  80  84
  93  94  95  97 101 111 113 114 117 123 138 148]
4교차검증 정확도 : 0.93333, 학습 데이터 크기 : 120, 테스트데이터 크기 : 30
4 검증세트 인덱스 : [  2   3   6   8  13  17  38  46  50  54  59  61  63  72  79  83  89  98
 100 112 115 119 120 125 126 134 135 136 139 147]
5교차검증 정확도 : 0.96667, 학습 데이터 크기 : 120, 테스트데이터 크기 : 30
5 검증세트 인덱스 : [  1  14  20  21  37  41  48  52  57  58  71  74  87  88  90  91  92  99
 102 103 106 107 116 121 124 129 130 140 144 149]
[1.0, 0.96667, 0.96667, 0.93333, 0.96667]
평균 검증 정확도 : 0.966